import AppKit
import CoveCore
import SwiftUI
import XCTest
@testable import Cove

@MainActor final class AssistantChatRenderingTests: XCTestCase {
  func testConversationAtDesignAndCompactSizesWithoutForegroundWindow() async throws {
    _ = NSApplication.shared
    DesignAssets.registerFonts()
    let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
    defer { try? FileManager.default.removeItem(at: directory) }
    let database = try Database(url: directory.appendingPathComponent("sample.sqlite"))
    let store = try AppStore(database: database, accountEmail: "alex@example.com", gmail: GmailClient(),
      gmailTokenProvider: { XCTFail("Rendering must not access Gmail"); return "test" }, syncClock: Date.init)
    store.isSample = true; store.screen = "mail"
    var mail = Mail(id: "launch", sender: "Maya Chen", senderEmail: "maya@example.com",
      subject: "Website launch — final sign-off", body: "Maya’s updates are ready. Your sign-off is the last step.", date: Date())
    mail.draft = "Thanks Maya, I’ll review the staging site."
    store.mails = [mail]; store.selectedID = mail.id
    let suite = "cove-assistant-render-" + UUID().uuidString
    let defaults = try XCTUnwrap(UserDefaults(suiteName: suite))
    defer { defaults.removePersistentDomain(forName: suite) }
    defaults.set(true, forKey: "ai.saved.openAI")
    let settings = AIProviderSettings(defaults: defaults, readSecret: { _ in XCTFail("No credentials needed"); return nil })
    settings.provider = .openAI; settings.setModel("gpt-6-sol", provider: .openAI)
    var exchange = ChatExchange(question: "What’s left for the website launch today?", mail: mail, scope: .email)
    exchange.answer = "Thursday’s launch is on track. One thing needs you today."
    exchange.passages = [MailPassage(mail: mail, text: mail.body)]
    exchange.source = "Generated by test model · selected email"
    try await render(store: store, settings: settings, exchanges: [exchange], available: CGSize(width: 800, height: 848), name: "design")
    var long = exchange
    long.answer = String(repeating: "A longer answer remains readable and scrolls above the composer. ", count: 25)
    long.passages += (1...2).map { index in
      var other = mail; other.id = "source-\(index)"; other.subject = "Additional launch context \(index)"
      return MailPassage(mail: other, text: "Related source details.")
    }
    try await render(store: store, settings: settings, exchanges: [long], available: CGSize(width: 560, height: 700), name: "compact-long")
    var markdown = exchange
    markdown.answer = """
    ## One thing needs you

    **Review the staging site** before the launch. Maya has finished her updates.

    - Check the homepage and sign-up form.
      - Confirm the links work.
    - Reply with your approval or requested changes.

    > The email asks for your sign-off today.

    | Task | Owner |
    | --- | --- |
    | Site updates | Maya |
    | Final approval | You |

    Use `subject:launch` to find related messages. [1]
    """
    try await render(store: store, settings: settings, exchanges: [markdown], available: CGSize(width: 560, height: 700), name: "markdown-compact")
    var failed = exchange; failed.answer = nil; failed.error = "The model couldn’t complete this request. Please try again."
    try await render(store: store, settings: settings, exchanges: [failed], available: CGSize(width: 800, height: 848), name: "error")
    XCTAssertEqual(store.mails.first?.draft, mail.draft, "Viewing chat must preserve the original draft")
  }

  func testGroundingCountsDistinctSourcesAndDoesNotClaimFailedLookupWasLive() {
    let mail = Mail(id: "one", sender: "Maya", senderEmail: "maya@example.com", subject: "Launch", body: "Details")
    var exchange = ChatExchange(question: "What is next?", mail: mail, scope: .email)
    exchange.passages = [MailPassage(mail: mail, text: "First passage"), MailPassage(mail: mail, text: "Second passage")]
    XCTAssertEqual(exchange.groundingLabel, "1 email used")
    exchange.passages = []; exchange.source = "Downloaded mail only · live Gmail count unavailable"
    XCTAssertFalse(exchange.groundingLabel.contains("Live Gmail"))
    exchange.isCalendar = true; exchange.eventCreated = true
    XCTAssertEqual(exchange.groundingLabel, "Event added")
  }

  private func render(store: AppStore, settings: AIProviderSettings, exchanges: [ChatExchange], available: CGSize, name: String) async throws {
    let width = min(800, available.width - 48), height = min(896, available.height - 48)
    let host = NSHostingView(rootView: AssistantView(store: store, availableSize: available,
      settings: settings, initialExchanges: exchanges))
    let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: width, height: height), styleMask: [.borderless], backing: .buffered, defer: false)
    window.isReleasedWhenClosed = false; window.contentView = host
    defer { window.close() }
    for _ in 0..<8 { host.layoutSubtreeIfNeeded(); try await Task.sleep(for: .milliseconds(30)) }
    XCTAssertFalse(window.isVisible, "Offscreen QA must not take the user's desktop")
    XCTAssertEqual(host.bounds.width, width, accuracy: 1)
    XCTAssertEqual(host.bounds.height, height, accuracy: 1)
    let bitmap = try XCTUnwrap(host.bitmapImageRepForCachingDisplay(in: host.bounds))
    host.cacheDisplay(in: host.bounds, to: bitmap)
    try XCTUnwrap(bitmap.representation(using: .png, properties: [:]))
      .write(to: URL(fileURLWithPath: "/tmp/cove-assistant-\(name).png"))
  }
}
